services:
  - type: web
    name: movie-app
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn movie_recommendation.wsgi"
    envVars:
      - key: DEBUG
        value: false
