# Generated by Django 5.2.1 on 2025-06-11 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_year', models.PositiveIntegerField()),
                ('rating', models.FloatField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('link', models.URLField(default='https://example.com')),
                ('genres', models.ManyToManyField(to='movie_app.genre')),
                ('languages', models.ManyToManyField(to='movie_app.language')),
            ],
        ),
        migrations.CreateModel(
            name='OTTPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='ott_logos/')),
                ('link', models.URLField(default='https://example.com')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ott_links', to='movie_app.movie')),
            ],
        ),
    ]
